
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-18T18:34:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1bcc8d793854df6d154933c6a3ad53a0e1f2d20",
 "version": "1.9.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
