
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-22T16:46:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7150a867e653c046c48f5bc89548b464a5c6008",
 "version": "2024.12.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
