from ur_material.modules.add_dots import *
from ur_material.modules.add_ink_leak import *
from ur_material.modules.add_shadow_final import *
from ur_material.modules.add_watermark import *
from ur_material.modules.bg_extraction import *
from ur_material.modules.color_extraction import *
from ur_material.modules.contains_gray import *
from ur_material.modules.elastic_transform import *
from ur_material.modules.general_quality_reduce import *
from ur_material.modules.half_paper import *
from ur_material.modules.ink_leak_final import *
from ur_material.modules.ink_reduce import *
from ur_material.modules.make_it_old_final import *
from ur_material.modules.overlap_final import *
from ur_material.modules.perspective_transform import *
from ur_material.modules.random_break_reduce import *
from ur_material.modules.rotate import *
from ur_material.modules.scanned import *
from ur_material.modules.seperate_binary import *
from ur_material.modules.seperate_lines import *
from ur_material.modules.texture_overlap import *
from ur_material.modules.warp_texture_blur_sticker import *