from typing import NoReturn

class EXCEPTION:
    __CRASH_REPORTS_PATH: str
    __TIME_STAMP_WHEN_LINPG_STARTED: str
    class Error(Exception):
        def __init__(self, *args: object) -> None: ...
    class FileNotExists(Exception):
        def __init__(self, *args: object) -> None: ...
    class FunctionIsNotImplemented(Exception):
        def __init__(self, *args: object) -> None: ...
    class ToolIsMissing(Exception):
        def __init__(self, *args: object) -> None: ...
    class SitePackageNotExists(Exception):
        def __init__(self, *args: object) -> None: ...
    @classmethod
    def __log(cls, msg: str) -> None: ...
    @staticmethod
    def get_python_version() -> str: ...
    @staticmethod
    def inform(info: str) -> None: ...
    @classmethod
    def warn(cls, info: str) -> None: ...
    @classmethod
    def fatal(cls, info: str, error_type_id: int = 0) -> NoReturn: ...
