# Generated by Django 3.0.13 on 2021-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.TextField(verbose_name='Queue')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('enqueued_at', models.DateTimeField(null=True, verbose_name='Enqueued at')),
                ('ended_at', models.DateTimeField(null=True, verbose_name='Ended at')),
            ],
            options={
                'verbose_name': 'job',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QueueModel',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, verbose_name='name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'queue',
                'permissions': [('manage', 'Can manage RQ jobs')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, verbose_name='name')),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('pid', models.PositiveIntegerField(verbose_name='PID')),
            ],
            options={
                'verbose_name': 'worker',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
