#-*-coding:utf-8;-*-
from enum import IntEnum
class hackrf_error(IntEnum):
    HACKRF_SUCCESS=0
    HACKRF_TRUE=1
    HACKRF_ERROR_INVALID_PARAM=-2
    HACKRF_ERROR_NOT_FOUND=-5
    HACKRF_ERROR_BUSY=-6
    HACKRF_ERROR_NO_MEM=-11
    HACKRF_ERROR_LIBUSB=-1000
    HACKRF_ERROR_THREAD=-1001
    HACKRF_ERROR_STREAMING_THREAD_ERR=-1002
    HACKRF_ERROR_STREAMING_STOPPED=-1003
    HACKRF_ERROR_STREAMING_EXIT_CALLED=-1004
    HACKRF_ERROR_USB_API_VERSION=-1005
    HACKRF_ERROR_NOT_LAST_DEVICE=-2000
    HACKRF_ERROR_OTHER=-9999
class hackrf_board_id(IntEnum):
    BOARD_ID_JELLYBEAN=0
    BOARD_ID_JAWBREAKER=1
    BOARD_ID_HACKRF1_OG=2
    BOARD_ID_RAD1O=3
    BOARD_ID_HACKRF1_R9=4
    BOARD_ID_UNRECOGNIZED=0xfe
    BOARD_ID_UNDETECTED=0xff
class hackrf_board_rev(IntEnum):
    BOARD_REV_HACKRF1_OLD=0
    BOARD_REV_HACKRF1_R6=1
    BOARD_REV_HACKRF1_R7=2
    BOARD_REV_HACKRF1_R8=3
    BOARD_REV_HACKRF1_R9=4
    BOARD_REV_HACKRF1_R10=5
    BOARD_REV_GSG_HACKRF1_R6=0x81
    BOARD_REV_GSG_HACKRF1_R7=0x82
    BOARD_REV_GSG_HACKRF1_R8=0x83
    BOARD_REV_GSG_HACKRF1_R9=0x84
    BOARD_REV_GSG_HACKRF1_R10=0x85
    BOARD_REV_UNRECOGNIZED=0xfe
    BOARD_REV_UNDETECTED=0xff
class hackrf_usb_board_id(IntEnum):
    USB_BOARD_ID_JAWBREAKER=0x604b
    USB_BOARD_ID_HACKRF_ONE=0x6089
    USB_BOARD_ID_RAD1O=0xcc15
    USB_BOARD_ID_INVALID=0xffff
class rf_path_filter(IntEnum):
    RF_PATH_FILTER_BYPASS=0
    RF_PATH_FILTER_LOW_PASS=1
    RF_PATH_FILTER_HIGH_PASS=2
class operacake_ports(IntEnum):
    OPERACAKE_PA1=0
    OPERACAKE_PA2=1
    OPERACAKE_PA3=2
    OPERACAKE_PA4=3
    OPERACAKE_PB1=4
    OPERACAKE_PB2=5
    OPERACAKE_PB3=6
    OPERACAKE_PB4=7
class operacake_switching_mode(IntEnum):
    OPERACAKE_MODE_MANUAL=0
    OPERACAKE_MODE_FREQUENCY=1
    OPERACAKE_MODE_TIME=2
class sweep_style(IntEnum):
    LINEAR=0
    INTERLEAVED=1
SAMPLES_PER_BLOCK=8192
BYTES_PER_BLOCK=16384
MAX_SWEEP_RANGES=10
HACKRF_OPERACAKE_ADDRESS_INVALID=0xff
HACKRF_OPERACAKE_MAX_BOARDS=8
HACKRF_OPERACAKE_MAX_DWELL_TIMES=16
HACKRF_OPERACAKE_MAX_FREQ_RANGES=8
HACKRF_BOARD_REV_GSG=0x80
HACKRF_PLATFORM_JAWBREAKER=1
HACKRF_PLATFORM_HACKRF1_OG=2
HACKRF_PLATFORM_RAD1O=4
HACKRF_PLATFORM_HACKRF1_R9=8
BOARD_ID_HACKRF_ONE=hackrf_board_id.BOARD_ID_HACKRF1_OG
BOARD_ID_INVALID=hackrf_board_id.BOARD_ID_UNDETECTED