# types.ChatResponse { #chatlas.types.ChatResponse }

```python
types.ChatResponse(self, generator)
```

Chat response object.

An object that, when displayed, will simulatenously consume (if not
already consumed) and display the response in a streaming fashion.

This is useful for interactive use: if the object is displayed, it can
be viewed as it is being generated. And, if the object is not displayed,
it can act like an iterator that can be consumed by something else.

## Attributes {.doc-section .doc-section-attributes}

| Name    | Type         | Description                       |
|---------|--------------|-----------------------------------|
| content | [str](`str`) | The content of the chat response. |

## Properties {.doc-section .doc-section-properties}

consumed
    Whether the response has been consumed. If the response has been fully
    consumed, then it can no longer be iterated over, but the content can
    still be retrieved (via the `content` attribute).

## Methods

| Name | Description |
| --- | --- |
| [display](#chatlas.types.ChatResponse.display) | Display the content in a rich console. |
| [get_string](#chatlas.types.ChatResponse.get_string) | Get the chat response content as a string. |

### display { #chatlas.types.ChatResponse.display }

```python
types.ChatResponse.display()
```

Display the content in a rich console.

This method gets called automatically when the object is displayed.

### get_string { #chatlas.types.ChatResponse.get_string }

```python
types.ChatResponse.get_content()
```

Get the chat response content as a string.