from database_helper.database.models import (MstBrands, MstCategoriesMetadataInfo, MstCategories, MstFacebookGroups,
                                             MstTikTokSettings, MstBrandTwitterAccounts, MstTwitterAccounts,
                                             MstFacebookGroupsLog, MstTikTokSettingsLog, MstCMObrands,
                                             MstCMOBrandSectorsLog, MstCMOPages, MstAuthorizedTokens,
                                             MstCMOBrandSectors, MstGoogleMyBusinessAccounts, MstGoogleMyBusinessTokens,
                                             MstGoogleMyBusinessLocations, MstWorkFlowAlertSettings, MstCMOPagesLog,
                                             MstKeywordAdditionSettings, TwitterHistoricalDataOrderInfo,
                                             MstGoogleAlertSettings, IAppStoreSetting, GooglePlayStoreClientPackages,
                                             MstExcludeBrandList, MstGooglePlayStoreTokens, MstComplaintsSettings,
                                             MstReachImpressionFormula, MstCategoryBrandGroups, MstCategoryGroupDetails,
                                             MstDefaultReachAndImpressionFormula, MstECommerceSettings,
                                             MstTripAdvisorAccounts, MstBookingSettings, MstBookingSettingsLog,
                                             TwitterGnipRules, InfluencerDetails)


model_mapping = {
    "mstBrands": MstBrands.__table__,
    "mstCategories": MstCategories.__table__,
    "mstCategories_MetadataInfo": MstCategoriesMetadataInfo.__table__,
    "mstTikTokSettings": MstTikTokSettings.__table__,
    "mstBrandTwitterAccounts": MstBrandTwitterAccounts.__table__,
    "mstTwitterAccounts": MstTwitterAccounts.__table__,
    "MstFacebookGroups": MstFacebookGroups.__table__,
    "MstFacebookGroups_log": MstFacebookGroupsLog.__table__,
    "mstTikTokSettings_log": MstTikTokSettingsLog.__table__,
    "MstCMObrands": MstCMObrands.__table__,
    "MstCMOBrandSectors_log": MstCMOBrandSectorsLog.__table__,
    "MstCMOPages": MstCMOPages.__table__,
    "MstAuthorizedTokens": MstAuthorizedTokens.__table__,
    "MstCMOBrandSectors": MstCMOBrandSectors.__table__,
    "mstGoogleMyBusinessAccounts": MstGoogleMyBusinessAccounts.__table__,
    "mstGoogleMyBusinessTokens": MstGoogleMyBusinessTokens.__table__,
    "mstGoogleMyBusinessLocations": MstGoogleMyBusinessLocations.__table__,
    "MstWorkFlowAlertSettings": MstWorkFlowAlertSettings.__table__,
    "MstCMOPages_log": MstCMOPagesLog.__table__,
    "mstKeywordAdditionSettings": MstKeywordAdditionSettings.__table__,
    "Twitter_HistoricalData_OrderInfo": TwitterHistoricalDataOrderInfo.__table__,
    "mstGoogleAlertSettings": MstGoogleAlertSettings.__table__,
    "IAppStoreSetting": IAppStoreSetting.__table__,
    "GooglePlayStoreClientPackages": GooglePlayStoreClientPackages.__table__,
    "mstExcludeBrandList": MstExcludeBrandList.__table__,
    "mstGooglePlayStoreTokens": MstGooglePlayStoreTokens.__table__,
    "mstComplaintsSettings": MstComplaintsSettings.__table__,
    "MstReachImpressionFormula": MstReachImpressionFormula.__table__,
    "mstCategoryBrandGroups": MstCategoryBrandGroups.__table__,
    "mstCategoryGroupDetails": MstCategoryGroupDetails.__table__,
    "MstDefaultReachAndImpressionFormula": MstDefaultReachAndImpressionFormula.__table__,
    "mstECommerceSettings": MstECommerceSettings.__table__,
    "mstTripAdvisorAccounts": MstTripAdvisorAccounts.__table__,
    "mstbookingSettings": MstBookingSettings.__table__,
    "mstbookingSettings_LOG": MstBookingSettingsLog.__table__,
    "TwitterGnipRules": TwitterGnipRules.__table__,
    "InfluencerDetails": InfluencerDetails.__table__
}
