FLUX_BACKEND_PLUGIN_GROUP = "flux.backend"

DEFAULT_LOG_LEVEL = "INFO"

PRE_APPLY_DIRECTORY = "pre-apply"
POST_APPLY_DIRECTORY = "post-apply"

FLUX_CONFIG_FILE = "flux.toml"

FLUX_GENERAL_CONFIG_SECTION_NAME = "flux"
FLUX_BACKEND_CONFIG_SECTION_NAME = "backend"

FLUX_BACKEND_KEY = "backend"
FLUX_MIGRATION_DIRECTORY_KEY = "migration_directory"
FLUX_LOG_LEVEL_KEY = "log_level"
FLUX_APPLY_REPEATABLE_ON_DOWN_KEY = "apply_repeatable_on_undo"

FLUX_DEFAULT_MIGRATION_DIRECTORY = "migrations"
FLUX_DEFAULT_LOG_LEVEL = "INFO"
FLUX_DEFAULT_APPLY_REPEATABLE_ON_DOWN = True
