# generated by datamodel-codegen:
#   filename:  properties_directory/elemental/atomic_radius.json
#   version:   0.25.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Name(Enum):
    atomic_radius = "atomic_radius"


class Units(Enum):
    km = "km"
    m = "m"
    pm = "pm"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    fractional = "fractional"
    crystal = "crystal"
    cartesian = "cartesian"
    alat = "alat"


class AtomicRadius(BaseModel):
    name: Optional[Name] = None
    units: Optional[Units] = None
    value: float
