from apminsight.instrumentation.packages import (
    django,
    sqlite,
    mysql,
    flask,
    redis,
    jinja2,
    pymemcache,
    psycopg2,
    cassandra,
    memcache,
    bottle,
    cherrypy,
    pyramid,
    mako,
    genshi,
    http,
    httplib2,
    httpx,
    urllib,
    urllib3,
    concurrent_futures,
    asyncpg,
    aioredis,
    aiomysql,
    aredis,
    mongodb,
    starlette,
    fastapi,
    oracledb,
    pymssql,
    pyodbc,
    streamlit,
    tornado,
    async_cron,
    celery,
    gunicorn
)

modules_info = {}
modules_info.update(django.module_info)
modules_info.update(sqlite.module_info)
modules_info.update(mysql.module_info)
modules_info.update(flask.module_info)
modules_info.update(redis.module_info)
modules_info.update(jinja2.module_info)
modules_info.update(pymemcache.module_info)
modules_info.update(psycopg2.module_info)
modules_info.update(cassandra.module_info)
modules_info.update(memcache.module_info)
modules_info.update(bottle.module_info)
modules_info.update(cherrypy.module_info)
modules_info.update(pyramid.module_info)
modules_info.update(mako.module_info)
modules_info.update(genshi.module_info)
modules_info.update(http.module_info)
modules_info.update(httpx.module_info)
modules_info.update(httplib2.module_info)
modules_info.update(urllib.module_info)
modules_info.update(urllib3.module_info)
modules_info.update(concurrent_futures.module_info)
modules_info.update(asyncpg.module_info)
modules_info.update(aiomysql.module_info)
modules_info.update(aioredis.module_info)
modules_info.update(aredis.module_info)
modules_info.update(mongodb.module_info)
modules_info.update(starlette.module_info)
modules_info.update(fastapi.module_info)
modules_info.update(oracledb.module_info)
modules_info.update(pymssql.module_info)
modules_info.update(pyodbc.module_info)
modules_info.update(streamlit.module_info)
modules_info.update(tornado.module_info)
modules_info.update(async_cron.module_info)
modules_info.update(celery.module_info)
modules_info.update(gunicorn.module_info)
