from enum import Enum

class ModelNames(Enum):
    MST_BRANDS = 'MstBrands'
    MST_CATEGORIES_METADATA_INFO = 'MstCategoriesMetadataInfo'
    MST_CATEGORIES = 'MstCategories'
    MST_TIKTOK_SETTINGS = 'MstTikTokSettings'
    MST_BRAND_TWITTER_ACCOUNTS = 'MstBrandTwitterAccounts'
    MST_TWITTER_ACCOUNTS = 'MstTwitterAccounts'
    MST_FACEBOOK_GROUPS = 'MstFacebookGroups'
    MST_FACEBOOK_GROUPS_LOG = 'MstFacebookGroupsLog'
    MST_TIKTOK_SETTINGS_LOG = 'MstTikTokSettingsLog'
    MST_CMO_PAGES = 'MstCMOPages'
    MST_CMO_BRAND_SECTORS_LOG = 'MstCMOBrandSectorsLog'
    MST_CMO_BRANDS = 'MstCMObrands'
    MST_AUTHORIZED_TOKENS = 'MstAuthorizedTokens'
    MST_CMO_BRAND_SECTORS = 'MstCMOBrandSectors'
    MST_GOOGLE_MY_BUSINESS_ACCOUNTS = 'MstGoogleMyBusinessAccounts'
    MST_GOOGLE_MY_BUSINESS_TOKENS = 'MstGoogleMyBusinessTokens'
    MST_GOOGLE_MY_BUSINESS_LOCATIONS = 'MstGoogleMyBusinessLocations'
    MST_WORK_FLOW_ALERT_SETTINGS = 'MstWorkFlowAlertSettings'
    MST_CMO_PAGES_LOG = 'MstCMOPagesLog'
    MST_KEYWORD_ADDITION_SETTINGS = 'MstKeywordAdditionSettings'
    TWITTER_HISTORICAL_DATA_ORDER_INFO = 'TwitterHistoricalDataOrderInfo'
    MST_GOOGLE_ALERT_SETTINGS = 'MstGoogleAlertSettings'
    I_APP_STORE_SETTING = 'IAppStoreSetting'
    GOOGLE_PLAY_STORE_CLIENT_PACKAGES = 'GooglePlayStoreClientPackages'
    MST_EXCLUDE_BRAND_LIST = 'MstExcludeBrandList'
    MST_GOOGLE_PLAY_STORE_TOKENS = 'MstGooglePlayStoreTokens'
    MST_COMPLAINTS_SETTINGS = 'MstComplaintsSettings'
    MST_REACH_IMPRESSION_FORMULA = 'MstReachImpressionFormula'
    MST_CATEGORY_BRAND_GROUPS = 'MstCategoryBrandGroups'
    MST_CATEGORY_GROUP_DETAILS = 'MstCategoryGroupDetails'
    MST_DEFAULT_REACH_AND_IMPRESSION_FORMULA = 'MstDefaultReachAndImpressionFormula'
    MST_ECOMMERCE_SETTINGS = 'MstECommerceSettings'
    MST_TRIP_ADVISOR_ACCOUNTS = 'MstTripAdvisorAccounts'
    MST_BOOKING_SETTINGS = 'MstBookingSettings'
    MST_BOOKING_SETTINGS_LOG = 'MstBookingSettingsLog'
    TWITTER_GNIP_RULES = 'TwitterGnipRules'
    INFLUENCER_DETAILS = 'InfluencerDetails'

