# coding: utf-8

"""
    EHESO API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eheso_api_client.api.layer_info_api import LayerInfoApi  # noqa: E501


class TestLayerInfoApi(unittest.TestCase):
    """LayerInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LayerInfoApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_code_get(self) -> None:
        """Test case for code_get

        Single Layer Code Information  # noqa: E501
        """
        pass

    def test_field_get(self) -> None:
        """Test case for field_get

        Get Minimal Field Information  # noqa: E501
        """
        pass

    def test_layer_get(self) -> None:
        """Test case for layer_get

        Single Layer Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
