# coding: utf-8

"""
    EHESO API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eheso_api_client.models.error_schema import ErrorSchema  # noqa: E501

class TestErrorSchema(unittest.TestCase):
    """ErrorSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorSchema:
        """Test ErrorSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorSchema`
        """
        model = ErrorSchema()  # noqa: E501
        if include_optional:
            return ErrorSchema(
                var_date = '2024-10-29T21:20:06.997Z',
                status_code = 500,
                message = 'An error occurred',
                call_info = 'POST /api/v1/layer/COUNTRY/query'
            )
        else:
            return ErrorSchema(
        )
        """

    def testErrorSchema(self):
        """Test ErrorSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
