from setuptools import setup, find_packages

setup(
    name='stock_historic_data',
    version='0.1.1',
    package_dir={'': 'src'},
    packages=find_packages(where='src'),
    install_requires=[
        'appdirs==1.4.4',
        'beautifulsoup4==4.12.3',
        'blinker==1.7.0',
        'certifi==2024.2.2',
        'charset-normalizer==3.3.2',
        'click==8.1.7',
        'colorama==0.4.6',
        'Flask==3.0.2',
        'frozendict==2.4.0',
        'greenlet==3.0.3',
        'html5lib==1.1',
        'idna==3.6',
        'itsdangerous==2.1.2',
        'Jinja2==3.1.3',
        'lxml==5.1.0',
        'MarkupSafe==2.1.5',
        'multitasking==0.0.11',
        'numpy==1.26.4',
        'pandas==2.2.1',
        'peewee==3.17.1',
        'python-dateutil==2.9.0.post0',
        'pytz==2024.1',
        'pytest==7.4.0',
        'requests==2.31.0',
        'six==1.16.0',
        'soupsieve==2.5',
        'SQLAlchemy==2.0.27',
        'typing_extensions==4.10.0',
        'tzdata==2024.1',
        'urllib3==2.2.1',
        'webencodings==0.5.1',
        'Werkzeug==3.0.1',
        'yfinance==0.2.37',
    ],
    author='Abhinav Priyadarshi',
    author_email='abhinavpriyadarshi2020@gmail.com',
    description='A project to fetch and store historic and live stock data using the Yahoo Finance API.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/your-repo',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
    entry_points={
        'console_scripts': [
            'your_command=your_module:your_function',
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
