


__version__ = "0.2.0"

PYMODULE_VERSION = __version__

CORE_VERSION = "0.2.0"
PLATFORM_VERSION = "0.2.0"
SCALARS_VERSION = "0.0.9"
INTERVALS_VERSION = "0.2.0"
ALGEBRA_VERSION = "0.2.0"
STREAMS_VERSION = "0.2.0"
