# File types
JPG_FILE: str
MP4_FILE: str
LOG_FILE: str

# Cacheing configurations
CACHE_DIR: str
CACHE_FILE_PREFIX: str
PICKLE_FILE: str

# Logging configuration
BACKUP_FILES_COUNT: int
LOGS_DIR: str
LOG_INTERVAL: str
LOGGING_FORMAT: str

# Date and time formatting
YYMMDD_FORMAT: str
HHMMSS_UNDERSCORE_FORMAT: str
HHMMSS_COLON_FORMAT: str

# Status codes
OK_STATUS_CODE: int
NO_CONTENT_STATUS_CODE: int

# TimeLapseCreator default configurations
DEFAULT_PATH_STRING: str
DEFAULT_CITY_NAME: str
DEFAULT_SECONDS_BETWEEN_FRAMES: int
DEFAULT_NIGHTTIME_RETRY_SECONDS: int
DEFAULT_VIDEO_FPS: int
DEFAULT_VIDEO_WIDTH: int
DEFAULT_VIDEO_HEIGHT: int
