
#
# ===== Note =====
#
# This library was auto-generated by AG Remap's APIMirrorBuilder tool,
#   a build system tool used in AG Remap's CI pipeline that creates a mirror for the existing
#   API source code since we cannot rename the original name of 'FixRaidenBoss2' to 'Anime Game Remap' in Pypi,
#   therefore, we decided to make a brand new package that mirrors the original API.
#
# ***** APIMirrorBuilder Stats *****
#
# Version: 1.0.0
# Authors: Albert Gold#2696
# Datetime Ran: Sunday, December 22, 2024 01:52:25.816 PM UTC
# Run Hash: aa59901d-7aa2-460c-9f4d-4346fba962bf
# 
# **********************************
# ================
#

# ===== Anime Game Remap (AG Remap) =====
# Authors: NK#1321, Albert Gold#2696
#
# if you used it to remap your mods pls give credit for "Nhok0169" and "Albert Gold#2696"
# Special Thanks:
#   nguen#2011 (for support)
#   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
#   HazrateGolabi#1364 (for being awesome, and improving the code)

#
# ***** AG Remap Stats *****
#
# Version: 4.1.5
# Authors: NK#1321, Albert Gold#2696
# Datetime Compiled: Sunday, December 22, 2024 01:52:25.816 PM UTC
# Build Hash: 928f7813-1c6f-43dc-993c-194df6696dc5
#
# **************************
#

from FixRaidenBoss2 import remapMain

if __name__ == '__main__':
    remapMain()