
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-18T10:09:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "010ee993f3f157af68a147aedac91a304be2f658",
 "version": "1.8.102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
