"""
This type stub file was generated by pyright.
"""

from contextvars import ContextVar
from modal import App
from sqlalchemy.orm import Session
from app.db import CodemodRunModel, TaskEpicModel, TaskModel
from codegen.utils.modal.modal_context import ModalContext

logger = ...
execution_ctx: ContextVar[ModalContext] = ...
metadata_ctx: ContextVar[str] = ...
def get_modal_log_url() -> None | str:
    ...

def get_epic_for_function_execution(task: TaskModel | None = ..., codemod_run: CodemodRunModel | None = ...) -> TaskEpicModel | None:
    ...

def log_function_executions(db: Session, cm_run_ids: list[int], app: App | None = ...) -> None:
    ...

def log_function_execution(db: Session, cm_run_id: int, app: App | None = ...) -> None:
    ...

