"""
This type stub file was generated by pyright.
"""

from json import JSONEncoder

def chunk_list(lst: list, chk_size: int) -> list[list[str]]:
    ...

def flatten(nested_list: list[list]) -> list:
    ...

def newline_join(list_of_strings: list[str]) -> str:
    ...

def add_line_numbers(raw: str | None = ..., start_line: int = ...): # -> str:
    """Adds line numbers in, one-indexed"""
    ...

def hash_string(string: str): # -> str:
    ...

class DateTimeEncoder(JSONEncoder):
    def default(self, obj): # -> str | Any:
        ...
    


def json_dumps_safe(x: dict | list, indent: int = ...) -> str:
    ...

def del_dir(folder_path) -> None:
    ...

