# Generated by Django 4.0.7 on 2024-04-07 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0002_supplier_order_alter_supplier_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # set order as row number
            """
                UPDATE suppliers_supplier
                SET "order" = id
            """,
            migrations.RunSQL.noop,
        )
    ]
