
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-06T15:34:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2db2a90536a8ca61d438c341ac337cab81589889",
 "version": "0.37.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
