"""
Python MCU Bootloader
~~~~~~~~~~~~~~~~~~~~~

pymdfu is a Python driver for a MCU bootloader
"""
import logging
logging.getLogger(__name__).addHandler(logging.NullHandler())

# Build number part of version will be replaced by build number from Jenkins.
# For local builds the build number is 0 and the 'snapshot' is added as Local Version Identifier
__version__ = '2.5.1.9'

# The GIT commit ID and build date are generated by Jenkins when building the package
COMMIT_ID = '7846cbc0b89aa61d664aef528892d2daa5a42cc8'
BUILD_DATE = '2024-12-11 11:16:07'

