# generated by datamodel-codegen:
#   filename:  core/reusable/energy.json
#   version:   0.25.5

from __future__ import annotations

from enum import Enum
from typing import Union

from pydantic import BaseModel


class Units(Enum):
    kJ_mol = "kJ/mol"
    eV = "eV"
    J_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    rydberg = "rydberg"
    eV_atom = "eV/atom"


class Units22(Enum):
    eV_A_2 = "eV/A^2"


class EnergySchema(BaseModel):
    name: str
    units: Union[Units, Units22]
    value: float
