
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-19T19:30:39-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7bf76976ecd20b439aa30e22631224c51323474d",
 "version": "3.1.9.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
