# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class ProjectIdSnowflakeBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account': 'str',
        'password': 'str',
        'username': 'str'
    }

    attribute_map = {
        'account': 'account',
        'password': 'password',
        'username': 'username'
    }

    def __init__(self, account: 'str' =None, password: 'str' =None, username: 'str' =None):  # noqa: E501
        """ProjectIdSnowflakeBody - a model defined in Swagger"""  # noqa: E501
        self._account = None
        self._password = None
        self._username = None
        self.discriminator = None
        if account is not None:
            self.account = account
        if password is not None:
            self.password = password
        if username is not None:
            self.username = username

    @property
    def account(self) -> 'str':
        """Gets the account of this ProjectIdSnowflakeBody.  # noqa: E501


        :return: The account of this ProjectIdSnowflakeBody.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account: 'str'):
        """Sets the account of this ProjectIdSnowflakeBody.


        :param account: The account of this ProjectIdSnowflakeBody.  # noqa: E501
        :type: str
        """

        self._account = account

    @property
    def password(self) -> 'str':
        """Gets the password of this ProjectIdSnowflakeBody.  # noqa: E501


        :return: The password of this ProjectIdSnowflakeBody.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: 'str'):
        """Sets the password of this ProjectIdSnowflakeBody.


        :param password: The password of this ProjectIdSnowflakeBody.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def username(self) -> 'str':
        """Gets the username of this ProjectIdSnowflakeBody.  # noqa: E501


        :return: The username of this ProjectIdSnowflakeBody.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: 'str'):
        """Sets the username of this ProjectIdSnowflakeBody.


        :param username: The username of this ProjectIdSnowflakeBody.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectIdSnowflakeBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'ProjectIdSnowflakeBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectIdSnowflakeBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'ProjectIdSnowflakeBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
