# coding: utf-8

"""
    Secore API

    API for the Seres core platform

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seres_client.api.flight_plan_references_api import FlightPlanReferencesApi


class TestFlightPlanReferencesApi(unittest.TestCase):
    """FlightPlanReferencesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlightPlanReferencesApi()

    def tearDown(self) -> None:
        pass

    def test_get_mission_plan_reference(self) -> None:
        """Test case for get_mission_plan_reference

        Get Mission Plan Reference
        """
        pass

    def test_get_mission_plan_references(self) -> None:
        """Test case for get_mission_plan_references

        Get Mission Plan References
        """
        pass


if __name__ == '__main__':
    unittest.main()
