# coding: utf-8

"""
    Secore API

    API for the Seres core platform

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seres_client.api.resource_assembly_schema_energy_bank_components_api import ResourceAssemblySchemaEnergyBankComponentsApi


class TestResourceAssemblySchemaEnergyBankComponentsApi(unittest.TestCase):
    """ResourceAssemblySchemaEnergyBankComponentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResourceAssemblySchemaEnergyBankComponentsApi()

    def tearDown(self) -> None:
        pass

    def test_get_resource_assembly_schema_energy_bank_component(self) -> None:
        """Test case for get_resource_assembly_schema_energy_bank_component

        Get Resource Assembly Schema Energy Bank Component
        """
        pass

    def test_get_resource_assembly_schema_energy_bank_components(self) -> None:
        """Test case for get_resource_assembly_schema_energy_bank_components

        Get Resource Assembly Schema Energy Bank Components
        """
        pass


if __name__ == '__main__':
    unittest.main()
