# coding: utf-8

"""
    Secore API

    API for the Seres core platform

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seres_client.api.future_activities_api import FutureActivitiesApi


class TestFutureActivitiesApi(unittest.TestCase):
    """FutureActivitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FutureActivitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_future_activities(self) -> None:
        """Test case for get_future_activities

        Get Future Activities
        """
        pass


if __name__ == '__main__':
    unittest.main()
