# coding: utf-8

"""
    Secore API

    API for the Seres core platform

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seres_client.models.mission_plan_creation_request_status_enum import MissionPlanCreationRequestStatusEnum

class TestMissionPlanCreationRequestStatusEnum(unittest.TestCase):
    """MissionPlanCreationRequestStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMissionPlanCreationRequestStatusEnum(self):
        """Test MissionPlanCreationRequestStatusEnum"""
        # inst = MissionPlanCreationRequestStatusEnum()

if __name__ == '__main__':
    unittest.main()
