# coding: utf-8

"""
    Secore API

    API for the Seres core platform

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seres_client.models.future_entity_type import FutureEntityType

class TestFutureEntityType(unittest.TestCase):
    """FutureEntityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFutureEntityType(self):
        """Test FutureEntityType"""
        # inst = FutureEntityType()

if __name__ == '__main__':
    unittest.main()
