# coding: utf-8

"""
    Secore API

    API for the Seres core platform

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seres_client.models.app_missions_templates_schemas_mission_template_waypoint_schema_waypoint_coordinate_schema_output import AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput

class TestAppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput(unittest.TestCase):
    """AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput:
        """Test AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput`
        """
        model = AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput()
        if include_optional:
            return AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput(
                longitude = '',
                latitude = '',
                altitude = '',
                elevation = ''
            )
        else:
            return AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput(
                longitude = '',
                latitude = '',
                altitude = '',
        )
        """

    def testAppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput(self):
        """Test AppMissionsTemplatesSchemasMissionTemplateWaypointSchemaWaypointCoordinateSchemaOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
