# Generated by Django 5.0.9 on 2024-10-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_infra', '0002_rename_site_type_industrial_sopinfra_site_type_indus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopinfra',
            old_name='swanha',
            new_name='sdwanha',
        ),
    ]
