# Generated by Django 5.0.9 on 2024-11-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('sop_infra', '0016_alter_prismaaccesslocation_compute_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prismacomputedaccesslocation',
            name='sop_infra_prismacomputedaccesslocation_name_slug_strataid_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='prismacomputedaccesslocation',
            name='sop_infra_prismacomputedaccesslocation_name_slug_strataid_not_empty',
        ),
        migrations.AddConstraint(
            model_name='prismacomputedaccesslocation',
            constraint=models.CheckConstraint(check=models.Q(('name', None), _negated=True), name='sop_infra_prismacomputedaccesslocation_name_none', violation_error_message='Name must be set.'),
        ),
        migrations.AddConstraint(
            model_name='prismacomputedaccesslocation',
            constraint=models.CheckConstraint(check=models.Q(('slug', None), _negated=True), name='sop_infra_prismacomputedaccesslocation_slug_none', violation_error_message='Slug must be set.'),
        ),
    ]
