# Generated by Django 5.0.9 on 2024-11-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('sop_infra', '0018_alter_prismacomputedaccesslocation_strata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prismaendpoint',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.ipaddress'),
        ),
    ]
